### ISSUE TITLE
Filter adapter must support nested properties

### ISSUE THREAD

**Issue by brendt** [pageon/stitcher-core#1]
By supporting nested properties, complexer adapter settings like the following are possible.

```yaml
adapters:
    filter:
        posts:
            category.name: foo
```
